version: '3.8'
services:
  web:
    build: .
    command:  bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py loaddata 'fixtures/auth.json' && python manage.py loaddata 'fixtures/cardmanagement.json' && python manage.py loaddata 'fixtures/testingapp.json' && python manage.py runserver 0.0.0.0:8000"
#    command: python main.py
    ports:
      - 0.0.0.0:8001:8000
