FROM python:3.9
ENV PYTHONUNBUFFERED 1
RUN mkdir /avdeev
WORKDIR /avdeev
ENV APP_HOME=/avdeev
COPY requirements.txt /avdeev/

RUN apt update && apt -y install nano python3-pip
RUN pip install --upgrade pip && pip install -r requirements.txt
ADD . /avdeev/
