# Generated by Django 4.1.3 on 2022-12-11 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardBaseTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_series', models.IntegerField(verbose_name='Серия карты')),
                ('card_number', models.IntegerField(verbose_name='Номер карты')),
                ('card_create_date', models.DateTimeField(verbose_name='Дата выпуска карты')),
                ('card_end_date', models.DateTimeField(verbose_name='Дата окончания карты')),
                ('card_last_use', models.DateTimeField(verbose_name='Дата последнего использования карты')),
                ('card_amount', models.IntegerField(verbose_name='Баланс')),
            ],
            options={
                'verbose_name': 'Подарочная карта',
                'verbose_name_plural': 'Подарочные карты',
            },
        ),
        migrations.CreateModel(
            name='OperationCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Operation_name', models.CharField(max_length=200, verbose_name='Название статуса')),
            ],
            options={
                'verbose_name': 'Операция по карте',
                'verbose_name_plural': 'Операции по картам',
            },
        ),
        migrations.CreateModel(
            name='StatusCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status_name', models.CharField(max_length=200, verbose_name='Название статуса')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='CardHistoryUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_operation_detail', models.CharField(blank=True, max_length=200, null=True, verbose_name='Детали операции')),
                ('card_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cardmanagement.cardbasetable', verbose_name='Номер карты')),
                ('card_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cardmanagement.operationcard', verbose_name='Операция по карте')),
            ],
            options={
                'verbose_name': 'История операций по карте',
                'verbose_name_plural': 'История операций по картам',
            },
        ),
        migrations.AddField(
            model_name='cardbasetable',
            name='card_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cardmanagement.statuscard', verbose_name='Статус'),
        ),
    ]
